// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDURsm2RcpCsILoSC4NOV0dchmNCJ6GXAA',
    appId: '1:199778574831:web:60bfe5726448a722e6d61a',
    messagingSenderId: '199778574831',
    projectId: 'to-doist-73d6f',
    authDomain: 'to-doist-73d6f.firebaseapp.com',
    storageBucket: 'to-doist-73d6f.appspot.com',
    measurementId: 'G-V7DGW8XNF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa9nXzwulofTD9dQWMaq6USUJqwOGVP1k',
    appId: '1:199778574831:android:c701835613397313e6d61a',
    messagingSenderId: '199778574831',
    projectId: 'to-doist-73d6f',
    storageBucket: 'to-doist-73d6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQcmyADlDx0WX-6idd_BrndBzP37-Oq0w',
    appId: '1:199778574831:ios:a23297bdb62fa304e6d61a',
    messagingSenderId: '199778574831',
    projectId: 'to-doist-73d6f',
    storageBucket: 'to-doist-73d6f.appspot.com',
    androidClientId: '199778574831-ud8uqvdhoa0lcnmvudmpfo40ntrokpbh.apps.googleusercontent.com',
    iosClientId: '199778574831-sov0vdpeilhck5gmurn9j5q2lof80kia.apps.googleusercontent.com',
    iosBundleId: 'com.example.todist',
  );
}
